import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { RootStyleRegistry } from "@/util/root-style-registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Full Stack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <RootStyleRegistry>
        <body className={inter.className}>{children}</body>
      </RootStyleRegistry>
    </html>
  );
}
